<?php
/**
 * @file
 * rCredits
 *
 * A module for the rCredits financial system.
 * This module implements rCredits as an extension to Community Accounting (mcapi).
 *
 * PURPOSE:
 * Specifically, this module keeps track of and manages the following:
 * - balances: how much credit each participating individual or enterprise has been given,
 *             toward future goods and services
 * - credit lines: how much advance credit each participant has been (or is to be) granted, with
 *             the expectation that they will produce commensurate goods and services
 * - transactions: exchanges of credit for goods and services or for other types of credit
 * - credit issuance: how credit comes into being, before it is used in transactions
 *
 * CREDIT ISSUANCE:
 * In the rCredits system, credit is always issued as a Ricardian Contract
 * (see http://www.systemics.com/docs/ricardo/issuer/contract.html).
 * Initially, for the first 6 months, credit will be issued only by the Society to Benefit Everyone, Inc.,
 * for rebates, bonuses, and inflation adjustments. That credit will be backed by the membership
 * promise of each participant.
 *
 * After 6 months, we expect that Common Good Communities will be the sole issuers of rCredits.
 * At that time, all participants will exchange their rCredits one-for-one for new rCredits issued
 * jointly by themselves (that is, by their Common Good Community). The new contract will spell out
 * the financial relationship between Common Good Communities.
 *
 * STRUCTURE:
 * rCredits is the central engine
 * separate modules handle the various transaction channels: rSMS, rSmartphone, rBrowser, etc.
 * rIssue handles credit issuance.
 * 
 * a companion module, rDemocracy, handles participatory financial decision-making
 */

require_once 'rcredits.inc';
require_once 'rcredits-backend.inc';
require_once 'rcron/rcron.inc'; // required here by cron
use rCredits as r;
use rCredits\Util as u;
use rCredits\Testing as t;

define('R_SYS_ERR', "The rCredits System has detected an unusual problem. If your activity was interrupted, please feel free to try again.<br>\n");

class rCreditsMailSystem extends DefaultMailSystem {
  public function format(array $message) {
    $message['body'] = drupal_wrap_mail(join("\n\n", $message['body']));
    return $message;
  }
}


/**
 * Top level exception handler (not a hook)
 * Log the error and follow up according to channel.
 *   Web: Jump to default member page and display a complete error message.
 *   SMS: Give a short apology.
 *   Smart: Give a short apology.
 *   Uninitialized: print the full error information and die
 */
function rcredits_exception_handler($e) {
  global $channel, $rsms_number;
  global $R_FATAL_ERROR;
  
  list ($msg, $line0, $file0, $trace) = array($e->getMessage(), $e->getLine(), $e->getFile(), $e->getTrace());
  $file0 = basename($file0);
  $trace_msg = '';
  for ($i = 0; $i < 11; $i++) {
    $line = $file = '';
    @extract($trace[$i]); // (file, line, function, args) OR just (function, args)
    $line = @$line ?: '';
    $file = basename(@$file);
    $function = basename(@$function);
/**/ $args = preg_replace('/Array\s+\(/sm', 'Array', print_r(@$args, 1)); // keep
    $args = substr($args, 6); // discard the gratuitous "Array" at the start
    $args = preg_replace('/$\s*\)$\s$/sm', '', $args);
    $args = '    ' . str_replace("\n", "<br>\n    ", $args);
    $args = str_replace('  ', ' &nbsp;', $args);
    $trace_msg .= "<br>\n- $line in $file, calling $function() with:<br>\n$args";
  }
///    $trace = str_replace('<!--', '<! --', print_r($trace, 1));
//    $trace_msg .= "<!--$trace-->"; // source will contain the whole trace
  $msg = '<b>Exception:</b>' . R_SYS_ERR. "<br>\n($msg)<br>\n- $line0 ($file0)" . $trace_msg;
  $message = str_replace('&nbsp;', '', str_replace('<br>', '', $msg));
  if (!isDEV) {
    if (isPRODUCTION) mail(R_TESTER_EMAIL, 'rCredits FATAL ERROR', $message);
    $R_FATAL_ERROR = u\loga('FATAL', compact('message')); // this gets picked up by rcredits_shutdown()
/**/  die(); // invoke shutdown
  } else echo 'FATAL ERROR: ' . $msg;
}

/**
 * Implements hook_boot().
 */
function rcredits_boot() {
  drupal_register_shutdown_function('rcredits_shutdown');
  set_exception_handler('rcredits_exception_handler');
}

/**
 * Shutdown function to redirect to error page, if there is an error.
 */
function rcredits_shutdown() {
  global $R_FATAL_ERROR;
  if (@$R_FATAL_ERROR) \drupal_goto('error/' . $R_FATAL_ERROR);
}

/**
 * Implements hook_im_send().
 */
function rcredits_im_send($index, &$message, $subs) {
  return FALSE; // can't send IMs yet

  $message['send'] = FALSE; // disable emailing, since we sent it by IM instead
  return TRUE;
} 

/**
 * Implements hook_mail().
 * @param string $index: filename of email template and index into subjects array
 * @param assoc $msg_array: standard drupal message components: [subject, body, headers]
 * @param assoc $info: substitutions for message body and subject
 * @see also: r\notify() and _user_mail_notify
 */
function rcredits_mail($index, &$msg_array, $info) {
//    $data['user'] = r\acct()->account();
//    user_mail_tokens($variables, $data, compact('language')); // adds links for password reset and account cancelation
    $index = str_replace('_', '-', $index); // correct Drupal template names to rCredits standard
//    if (rcredits_im_send($index, $msg_array, $info)) return; // If we can send by instant-message, do not send by email.
    
    if ($uid = (int) @$info['uid']) {
      //u\EXPECT($uid, 'bad uid in mail');
      $acct = r\acct($uid);
      $info += (array) $acct->account();
      $info['quid'] = $acct->mainQid;
      $langcode = $acct->language->language; // instead of $language = $msg_array['language']; 
      $info['shortName'] = $acct->name;
    }
// NOT USED (by policy)  $info['oneTimeLoginUrl'] = \user_pass_reset_url($acct->account());
    $info['site'] = R_SITE_URL;
    $info['region'] = strtolower(R_SERVER_ID);

    $email = $info['email'];
///    foreach ($info as $k => $v) if (is_object($v) or is_array($v)) mail('wspademan@gmail.com', 'acct obj in _mail', print_r(compact('index','msg_array','info','uid','k','v'), 1) . print_r(debug_backtrace(), 1));
    foreach ($info as $k => $v) if (!is_object($v) and !is_array($v)) $subs['{' . $k . '}'] = $v;
    $msg_array['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed'; // default is plain text
    $message = @$info['noFrame'] ? r\emailTemplate($index) : r\emailBody($index);

    $subject = @$info['subject'] ?: $GLOBALS['emailSubjects'][$index];
    $subject = $msg_array['subject'] = strtr($subject, $subs);
    $message = $msg_array['body'][] = strtr($message, $subs);

    $message = str_replace("\r\n", '', $message); // easier reading for log and tests
    $fields = compact(u\ray('index email subject message'));
/**/ t\output('Actual (in hook_mail) ' . print_r($fields, 1), 'email');

    foreach (u\ray(R_NOLOG) as $one) $fields['message'] = str_replace(@$info[$one], '(?)', $message); // no secret
    u\loga('email', $fields, @$acct);
}

/**
 * Implements hook_page_alter().
 * Used in testing.
  0 => '#show_messages',
  1 => '#theme',
  2 => '#theme_wrappers',
  3 => '#type',
  4 => 'content',
  5 => 'page_top',
  6 => '#post_render',
 */
function rcredits_page_alter($page) {
/// debug($page['#type']);
/// debug(strip_tags($page['content']['system_main']['main']['#markup']));
}

/**
 * Implements hook_cron().
 */
function rcredits_cron() {
  rCredits\Cron\periodic();
}


/**
 * Implements hook_cron_queue_info().
 */
function rcredits_cron_queue_info() {
  $q = r\makeQueue('doTask', R_CRON_PERIOD - R_MAX_TASK_TIME); // make sure it finishes before the next period
  return compact('q');
}

/**/ function bs($n, $list = B_LIST) {debug(a\flagsDesc($n, $list));}
/**/ function tm($n) {debug($result = is_numeric($n) ? date('m-d-Y H:i:s a', $n) : strtotime($n)); return $result;}
function a($id) {global $lastA; return $lastA = r\acct(r\fullQid(strlen($id) == 3 ? '.' . $id : $id));}
function x($xid) {r\x($xid);}
//function us($a = '') {global $lastA; return new r\usd($a ? (is_object($a) ? $a : a($a)) : $lastA);}
/**/ function da($idfield) {list ($id, $field) = u\ray($idfield); debug(a($id)->$field);}
/**/ function step($a) {debug(us($a)->step());}
function ctty($id) {return a(a($id)->community);}
function ray() {return call_user_func_array('\\rCredits\\Util\\ray', func_get_args());}

/**
 * f('u.func arg1 arg2') OR f('u.func', arg1, arg2)
 */
function f($func) {
  $args = func_get_args();
  if (strpos($func, ' ') and count($args) == 1) $args = u\ray($args[0]);
  $func = array_shift($args);
  
  list ($n, $func) = explode('.', $func);
  $funcs = u\ray('r w s u be db t p a cr', '', 'Web', 'Smart', 'Util', 'Backend', 'DB', 'Testing', 'SMS', 'Admin', 'Cron');
  $func = 'rCredits\\' . ($funcs[$n] ? $funcs[$n] . '\\' : '') . $func;
  return call_user_func_array($func, $args);
}

/**
 * Show the function result in the debug window and return the result.
 * For example, d('u.fmtAmt 35.2') would show and return rCredits\Util\fmtAmt(35.2) = "$35.20".
 */
/**/ function d($s) {debug($result = call_user_func_array('f', func_get_args()));}

define('ONE_CRON_OP', 'one cron op'); // flags a call of cron() in PHP window

/**
 * Run a background op in the foreground (not on production server).
 */
function cron($op) {
/**/ if (isPRODUCTION) return debug("Don't run cron this way on production server.");
  global $testOnly; if(@$testOnly) return FALSE;
  global $cronOp; $cronOp = ONE_CRON_OP;
  $func = "rCredits\\Cron\\$op";
  return $func();
}

/*
  SELECT 
    u.fullName, 
    SUM(IF(t.payee=u.uid, amount, 0)) AS `in`,
    SUM(IF(t.payer=u.uid, amount, 0)) AS `out`, 
    SUM(IF(t.type=1, 0, t.r)) AS rewards,
    u.r+u.usd AS bal, u.rewards AS rewards2
    FROM r_txs t, users u
    WHERE (t.payer=u.uid OR t.payee=u.uid) GROUP BY u.uid

  SELECT 
    u.fullName, 
    SUM(IF(t.payee=u.uid, 1, 0)) AS `in`,
    SUM(IF(t.payer=u.uid, 1, 0)) AS `out`, 
    SUM(IF(t.type=1, 0, 1)) AS rewards
    FROM r_txs t, users u
    WHERE (t.payer=u.uid OR t.payee=u.uid) AND t.amount>0 GROUP BY u.uid
    
  SELECT u.fullName, SUM(-t.amount) AS bank FROM r_usd t, users u WHERE t.payer=u.uid AND t.payee=0 GROUP BY u.uid ORDER BY u.uid
  
  SELECT u.fullName, SUM(t.r) AS virtual FROM r_txs t LEFT JOIN users u ON u.uid=t.payee WHERE t.payeeFor LIKE '%virtual%' GROUP BY u.uid
  SELECT u.fullName, SUM(t.r) AS virtual FROM r_txs t LEFT JOIN users u ON u.uid=t.payer WHERE t.payerFor LIKE '%virtual%' GROUP BY u.uid
  
  $a = rCredits\acct('NEW.AAD');
$usa = new rCredits\usd($a); */
/// $usa->each('print_r', 0, array('deposit','withdrawal','fee'));
/*
function test() {
  include_once __DIR__ . '/usd.class';
  $usdW = new r\usd($w = r\acct(410044001));
  $usdA = new r\usd($a = r\acct(410061551));
/// debug($usdW->bal()); // keep
  $tx = $usdW->bank(-1, $err);
/// debug($tx.$err); // keep
  $usdW->each('test1', strtotime('60 days ago'), array('deposit'));
}*/
