<?php
/**
 * @file
 * rSMS (rCredits SMS Interface)
 *
 * An interface module for the rCredits financial system.
 */

use rCredits as r;
require_once __DIR__ . '/../rCredits.inc';
require_once __DIR__ . '/rSMS.inc';
require_once __DIR__ . '/rSMS-call.inc';

/**
 * SMS Incoming implements hook sms_incoming
 *
 * @param $op
 *   'pre process', 'process', 'post process'
 *
 * @param string $number
 *   the calling phone number
 *
 * @param string $message
 *   the incoming message
 */
function rSMS_sms_incoming($op, $number, $message) {
  switch ($op) {
    case 'pre process':
      break;
    case 'process':
      $call = new r\SMS\call($number, $message);
      r\SMS\send($number, RSMS_PREFIX . trim($call->handle_call()));
      break;
    case 'post process':
      break;
  }
}
