<?php
/**
 * @file
 * rSMS (rCredits SMS)
 *
 * An interface module for the rCredits financial system.
 */

use rCredits as r;
require_once __DIR__ . '/../rcredits.inc';
require_once __DIR__ . '/rsms.inc';
require_once __DIR__ . '/rsms_call.inc';

/**
 * implements hook_form_alter, to set focus
 *
 * Insert a snippet of javascript in the page footer, to set the focus automatically
 * on the message field of the SMS simulation form.
 */
function rsms_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'sms_devel_receive_form') {
    drupal_add_js("document.getElementById('edit-message').focus();", array('type'=>'inline', 'scope'=>'footer'));  
  }
}

/* probably delete this function
function rsms_settings(){
  $form['responses'] = array(
    '#title' => t('SMS Settings'),
    '#description' => t('You cannot change the SMS syntax here.'),
    '#type' => 'fieldset',
    '#weight' => -2
  );
  return system_settings_form($form);
}
*/

/**
 * SMS Incoming implements hook sms_incoming
 *
 * @param $op
 *   'pre process', 'process', 'post process'
 *
 * @param string $number
 *   the calling phone number
 *
 * @param string $message
 *   the incoming message
 */
function rsms_sms_incoming($op, $number, $message) {
  switch ($op) {
    case 'pre process':
      break;
    case 'process':
      $call = new r\SMS\call($number, $message);
      r\SMS\send($number, RSMS_PREFIX . $call->handle_call());
      break;
    case 'post process':
      break;
  }
}
