<?php
/**
 * @file
 * Install, update and uninstall functions for the rsms module (rCredits SMS).
 */

/**
 * Implement hook_install().
 *//*
function rsms_install() {
  $rsms_permissions = array(
    'receive sms',
//    'edit own sms number',
//    'transact via sms',
  );
  user_role_grant_permissions(DRUPAL_AUTHENTICATED_RID, $rsms_permissions);
  
  variable_set('user_register', 1); // means automatically register users by SMS
}

*/