<?php
/**
 * @file
 * rCredits Web Interface
 *
 * An interface module for the rCredits financial system.
 *
 * Note: to display one of the blocks defined herein on a page, use
 * echo render(rweb_block_view('blockname'));)
 */

use rCredits as r;
use rCredits\API as api;
use rCredits\Util as u;

require_once __DIR__ . '/../rcredits.inc';
require_once __DIR__ . '/rweb.inc';
require_once __DIR__ . '/../rsmart/rsmart.inc'; // for smart api menu entry

//define('RWEB_BLOCKS', 'accounts payment buy_now example_store charge exchange manage tx_period txs manage_account');
define('RWEB_BLOCKS', 'accounts');

/**
 * Implements hook_block_info().
 */
function rweb_block_info() {
  $info = array();
  foreach (u\ray(RWEB_BLOCKS) as $one) {
    $def = array('info' => ucfirst($one) . ' Block');
    if ($one == 'accounts') {
      $region = 'header';
//      $visibility = BLOCK_VISIBILITY_LISTED;
//      $pages = "members\nmembers/*";
      $status = 1;
      $def += compact(u\ray('region status'));
    }
    $info[$one] = $def;
  }
  return $info;
}

/**
 * Implements hook_block_view().
 */
function rweb_block_view($delta = '') {
  if (in_array($delta, u\ray(RWEB_BLOCKS))) return r\Web\blockView(NULL, r\Web\show_form($delta)); // no subject for blocks
}

/**
 * Implements hook_menu().
 MENU_CALLBACK	Menu type -- A hidden, internal callback, typically used for API calls.
MENU_DEFAULT_LOCAL_TASK	Menu type -- The "default" local task, which is initially active.
MENU_LOCAL_ACTION	Menu type -- An action specific to the parent, usually rendered as a link.
MENU_LOCAL_TASK	Menu type -- A task specific to the parent item, usually rendered as a tab.
MENU_NORMAL_ITEM	Menu type -- A "normal" menu item that's shown in menu and breadcrumbs.
MENU_SUGGESTED_ITEM	Menu type -- A normal menu item, hidden until enabled by an administrator.
 */
function rweb_menu() {
  $anyone = array('access callback' => TRUE, 'access arguments' => NULL);
  $smart = array('module' => 'rsmart', 'file' => 'rsmart.inc');
  $modal = array('modal' => TRUE);
  
  $menu = array(
    'summary' => r\Web\menu(t('Summary'), MENU_NORMAL_ITEM, 'show_form', array('home'), 'read transactions'),
    'transactions' => r\Web\menu(t('Transactions'), MENU_NORMAL_ITEM, 'show_form', array('txs', 1, 2), 'read transactions'),
    'charge' => r\Web\menu(t('Charge'), MENU_NORMAL_ITEM, 'show_form', array('tx', 'Charge', 1), 'sell'),
    'pay' => r\Web\menu(t('Pay'), MENU_NORMAL_ITEM, 'show_form', array('tx', 'Pay', 1), 'buy and sell'),
    'exchange' => r\Web\menu(t('Get rCredits / USD'), MENU_NORMAL_ITEM, 'show_form', array('exchange'), 'manage account'),
    'directory' => r\Web\menu(t('Find Businesses'), MENU_NORMAL_ITEM, 'show_form', array('directory'), 'sell'),

    'sms' => r\Web\menu('Test SMS', MENU_NORMAL_ITEM, 'show_form', array('sms'), '', $anyone), // should be 'admin' not '',...
    'handy' => r\Web\menu('Handy Links', MENU_NORMAL_ITEM, 'handy_links', array(), 'admin'),

    'account' => r\Web\menu(t('Basic Account Settings'), MENU_CALLBACK, 'show_form', array('account'), 'manage account'),
    'account/overview' => r\Web\menu('Basic Account Settings', MENU_DEFAULT_LOCAL_TASK, 'show_form', array('account'), 'manage account'),
    'account/cell-access' => r\Web\menu(t('Cell Phone Access'), MENU_LOCAL_TASK, 'show_form', array('cell'), 'manage account'),
    'account/relations' => r\Web\menu(t('Relations'), MENU_LOCAL_TASK, 'show_form', array('relations'), 'manage account'),
    'account/contact-info' => r\Web\menu(t('Contact Information'), MENU_LOCAL_TASK, 'show_form', array('contact_info'), 'manage account'),
    'company-info' => r\Web\menu(t('Company Info'), MENU_LOCAL_TASK, 'show_form', array('company'), 'company'),
    'account/options' => r\Web\menu(t('Account Options'), MENU_LOCAL_TASK, 'show_form', array('options'), 'manage account'),
    'account/bank-info' => r\Web\menu(t('Bank Info'), MENU_LOCAL_TASK, 'show_form', array('bank'), 'manage account'),

    'membership' => r\Web\menu(t('Membership Status'), MENU_CALLBACK, 'show_form', array('membership'), 'manage account'),

    'member' => r\Web\menu('Company Profile', MENU_CALLBACK, 'show_form', array('profile'), '', $anyone),
    'rcredits/util' => r\Web\menu('Util', MENU_CALLBACK, 'rCredits\\Web\\util', array(2), 'admin'),
    'autocomplete' => r\Web\menu('Identify', MENU_CALLBACK, 'rCredits\\Web\\auto', array(1, 2, 3), '', $anyone),

    'rcredits/backend' => r\Web\menu('API', 0, 'rCredits\\API\\backend2', array(), '', $anyone),
    'api' => r\Web\menu('API', 0, 'rCredits\\Smart\\api', array(), '', $anyone),
    'error' => r\Web\menu('System Error', 0, 'rCredits\\error', array(1), '', $anyone),
    
    'pay-with-rcredits' => r\Web\menu('Pay With rCredits', MENU_CALLBACK, 'show_form', array('buy_now'), '', $anyone), // form will require login

//    'example-store' => r\Web\menu('Example Store', MENU_NORMAL_ITEM, 'show_form', array('example_store'), '', $anyone),
//    'modal' => r\Web\menu('Modal Test', MENU_CALLBACK, 'drupal_get_form', array('rCredits\\Web\\modal_form'), '', $anyone + $modal),
//    'ok' => r\Web\menu('Please Confirm', MENU_CALLBACK, 'show_form', array('ok'), '', $anyone + $modal),
  );
  return $menu;
}

function rweb_menu_alter(&$items) {
  unset($items['node']);
}

function rweb_form_user_register_form_alter(&$form, &$form_state, $form_id) {r\Web\register_form($form, $form_state);}
function rweb_form_user_login_block_alter(&$form, &$form_state, $form_id) {return r\Web\login_alter($form, $form_state);}
function rweb_form_user_login_form_alter(&$form, &$form_state, $form_id) {return r\Web\login_alter($form, $form_state);}
function rweb_user_login(&$edit, $account) {r\Web\login_followup($edit);} // Implements hook_user_login().

/*function rweb_form_user_profile_form_alter(&$form, &$form_state, $form_id) {
  $form['account']['pass']['#process'] = array('expand_password_confirm', 'yourmodule_password_confirm');
}*/
