<?php
/**
 * @file
 * Install, update and uninstall functions for the rWeb module.
 */

use rCredits as r;
use rCredits\Util as u;
use rCredits\API as api;

/**
 * Implement hook_install().
 */
function rweb_install() {
  r\Web\userMenuItem('help', 'Help');
  r\Web\userMenuItem('membership', 'Membership Status');
  r\Web\userMenuItem('account', 'Account Settings');
  r\dbQ("UPDATE {menu_links} SET hidden=1 WHERE menu_name='user-menu' AND link_path='user'");
}
