<?php
/**
 * @file
 * rCredits Web Interface
 *
 * An interface module for the rCredits financial system.
 *
 * Note: to display one of the blocks defined herein on a page, use
 * echo render(rweb_block_view('blockname'));)
 */

use \rCredits\Web as rWeb;
use \rCredits\API as api;
use \rCredits\Utilities as u;

require_once __DIR__ . '/../rcredits.inc';
require_once __DIR__ . '/rweb.inc';

//define('RWEB_BLOCKS', 'accounts payment buy_now example_store charge exchange manage tx_period txs manage_account');
define('RWEB_BLOCKS', 'accounts');

/**
 * Implements hook_block_info().
 */
function rweb_block_info() {
  $info = array();
  foreach (u\ray(RWEB_BLOCKS) as $one) {
    $def = array('info' => ucfirst($one) . ' Block');
    if ($one == 'accounts') {
      $region = 'header';
//      $visibility = BLOCK_VISIBILITY_LISTED;
//      $pages = "members\nmembers/*";
      $status = 1;
      $def += compact(u\ray('region status'));
    }
    $info[$one] = $def;
  }
  return $info;
}

/**
 * Implements hook_block_view().
 */
function rweb_block_view($delta = '') {
  if (in_array($delta, u\ray(RWEB_BLOCKS))) return rWeb\block_view(NULL, rWeb\show_form($delta)); // no subject for blocks
}

/**
 * Implements hook_menu().
 */
function rweb_menu() {
  $anyone = array('access callback' => TRUE, 'access arguments' => NULL);
  $modal = array('modal' => TRUE);
  
//  $can_create = api\access('create transactions');
  $menu = array(
//    'members' => rWeb\menu($can_create ? 'Members Section' : 'Transactions', MENU_NORMAL_ITEM, 'show_form', array($can_create ? 'tx' : 'txs', 2)),
//    'members' => rWeb\menu('Members Section', MENU_NORMAL_ITEM, 'show_form', array($can_create ? 'tx' : 'txs', 'Charge', 2)),
    'node' => rWeb\menu('Homey', MENU_CALLBACK, 'show_form', array('home'), 'read transactions'),
    'transactions' => rWeb\menu('Transactions', MENU_NORMAL_ITEM, 'show_form', array('txs', 1, 2), 'read transactions'),
    'charge' => rWeb\menu('Charge', MENU_NORMAL_ITEM, 'show_form', array('tx', 'Charge', 1), 'sell'),
    'pay' => rWeb\menu('Pay', MENU_NORMAL_ITEM, 'show_form', array('tx', 'Pay', 1), 'buy and sell'),
    'exchange' => rWeb\menu('Get rCredits / USD', MENU_NORMAL_ITEM, 'show_form', array('exchange'), 'manage account'),
    'directory' => rWeb\menu('Directory', MENU_NORMAL_ITEM, 'show_form', array('directory'), 'sell'),
    'cell-access' => rWeb\menu('Cell Access', MENU_NORMAL_ITEM, 'show_form', array('cell'), 'manage account'),
    'relations' => rWeb\menu('Relations', MENU_NORMAL_ITEM, 'show_form', array('relations'), 'manage account'),
    'company-info' => rWeb\menu('Company Info', MENU_NORMAL_ITEM, 'show_form', array('company'), 'company'),
    'bank-info' => rWeb\menu('Bank Info', MENU_NORMAL_ITEM, 'show_form', array('bank'), 'manage account'),
    'contact-info' => rWeb\menu('Contact Info', MENU_NORMAL_ITEM, 'show_form', array('contact_info'), 'manage account'),
    'account' => rWeb\menu('Account Info', MENU_NORMAL_ITEM, 'show_form', array('account'), 'manage account'),

    'pay-with-rcredits' => rWeb\menu('Pay With rCredits', MENU_CALLBACK, 'show_form', array('buy_now'), '', $anyone), // form will require login

//    'example-store' => rWeb\menu('Example Store', MENU_NORMAL_ITEM, 'show_form', array('example_store'), '', $anyone),
    'member' => rWeb\menu('Company Profile', MENU_CALLBACK, 'show_form', array('profile'), '', $anyone),
    'rCredits/util' => rWeb\menu('Util', MENU_CALLBACK, 'rCredits\\Web\\util', array(2), 'administer site configuration'),
    'autocomplete' => rWeb\menu('Identify', MENU_CALLBACK, 'rCredits\\Web\\auto', array(1, 2, 3), '', $anyone),
//    'ok' => rWeb\menu('Please Confirm', MENU_CALLBACK, 'show_form', array('ok'), '', $anyone + $modal),
    
    'handy' => rWeb\menu('Handy Links', MENU_NORMAL_ITEM, 'handy_links', array(), 'administer site configuration'),
    'rCredits/backend' => rWeb\menu('API', 0, 'rCredits\\API\\backend2', array(), '', $anyone),
    'api' => rWeb\menu('API', 0, 'rCredits\\API\\smart_api', array(), '', $anyone),
    
//    'modal' => rWeb\menu('Modal Test', MENU_CALLBACK, 'drupal_get_form', array('rCredits\\Web\\modal_form'), '', $anyone + $modal),
  );
  
  return $menu;
}

function rweb_form_user_register_form_alter(&$form, &$form_state, $form_id) {rWeb\register_form($form, $form_state);}
function rweb_form_user_login_block_alter(&$form, &$form_state, $form_id) {return rWeb\login_alter($form, $form_state);}
function rweb_form_user_login_form_alter(&$form, &$form_state, $form_id) {return rWeb\login_alter($form, $form_state);}
function rweb_user_login(&$edit, $account) {rWeb\login_followup($edit);} // Implements hook_user_login().

/**
 * Implements hook_user_logout().
 */
//function rweb_user_logout($account) {
//}

/**
 * Implements hook_user_categories().
 * /
function rweb_user_categories() {
  $categories['contact'] = array(
    'name' => 'contact',
    'title' => 'Contact Info',
    'weight' => 9,
  );
  $categories['mobile'] = array(
    'name' => 'mobile',
    'title' => 'Mobile',
    'weight' => 10,
  );
  return $categories;
}
*/

/**
 * Implements hook_user_view().
 * Example from sms_user
 * / 
function rweb_user_view($account, $view_mode) {
  global $user;
  if (user_access('receive sms', $account) && ($user->uid == $account->uid || user_access('administer smsframework'))) {
    if (isset($account->sms_user['status']) &&
            $account->sms_user['status'] == SMS_USER_PENDING) {
      drupal_set_message(t('You need to confirm your mobile number, <a href="@mobile_url">enter the confirmation code sent to your mobile</a>.', array('@mobile_url' => url('user/' . $account->uid . '/edit/mobile'))));
    }
    $account->content['sms'] = array(
      '#type' => 'user_profile_category',
      '#title' => t('Mobile'),
    );
    $account->content['sms']['number'] = array(
      '#type' => 'user_profile_item',
      '#title' => t(''),
      // @todo - theme function to format number.
      '#value' => isset($account->sms_user['number']) ? $account->sms_user['number'] : '',
    );
  }
}
*/