INSERT INTO `r_nonmembers` (`id`, `company`, `potential`) VALUES
(2, 'The Barn', 0),
(3, 'Sandri Oil', 0),
(4, 'Rice Oil', 0),
(5, 'Wilson''s', 0),
(6, 'Hope & Olive', 0),
(7, 'Aubuchon', 0),
(8, 'YMCA', 0),
(9, 'World Eye', 0),
(10, 'Garden Cinema', 0),
(11, 'RD Smith', 0),
(12, 'Radio Shack', 0),
(13, 'Tire Warehouse', 0),
(14, 'Green River Auto', 0),
(15, 'Farmers Exchange', 0);
